import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { EcountClient } from "../client/ecount-client.js";
import { registerTools, type ToolDefinition } from "./tool-factory.js";

const masterDataTools: ToolDefinition[] = [
  {
    name: "ecount_master_save_customer",
    description:
      "ECOUNT ERP에 거래처를 등록하거나 수정합니다. 새 거래처를 추가하거나 기존 거래처 정보를 변경할 때 사용합니다.",
    endpoint: "AccountBasic/SaveBasicCust",
    type: "save",
    listKey: "CustList",
    inputSchema: {
      BUSINESS_NO: z.string().describe("거래처코드"),
      CUST_NAME: z.string().describe("회사명"),
      BOSS_NAME: z.string().optional().describe("대표자명"),
      UPTAE: z.string().optional().describe("업태"),
      JONGMOK: z.string().optional().describe("종목"),
      TEL: z.string().optional(),
      EMAIL: z.string().optional(),
      POST_NO: z.string().optional().describe("우편번호"),
      ADDR: z.string().optional(),
      REMARKS: z.string().optional(),
      GUBUN: z.string().optional().describe("구분"),
      EMP_CD: z.string().optional().describe("담당사원코드"),
      G_GUBUN: z.string().optional().describe("거래처코드구분 (01:사업자등록번호, 02:주민등록번호, 03:외국인)"),
      G_BUSINESS_TYPE: z.string().optional().describe("세무신고거래처구분 (1:거래처동일, 2:검색입력, 3:직접입력)"),
      G_BUSINESS_CD: z.string().optional().describe("세무신고거래처코드"),
      TAX_REG_ID: z.string().optional().describe("종사업장번호"),
      FAX: z.string().optional(),
      HP_NO: z.string().optional().describe("모바일"),
      DM_POST: z.string().optional().describe("DM우편번호"),
      DM_ADDR: z.string().optional().describe("DM주소"),
      REMARKS_WIN: z.string().optional().describe("검색창내용"),
      FOREIGN_FLAG: z.string().optional().describe("외환거래처사용여부 (Y/N)"),
      EXCHANGE_CODE: z.string().optional().describe("외화코드"),
      CUST_GROUP1: z.string().optional().describe("거래처그룹1코드"),
      CUST_GROUP2: z.string().optional().describe("거래처그룹2코드"),
      URL_PATH: z.string().optional().describe("홈페이지"),
      OUTORDER_YN: z.string().optional().describe("출하대상거래처구분 (Y/N)"),
      IO_CODE_SL: z.string().optional().describe("거래유형(영업) 부가세코드"),
      IO_CODE_BY: z.string().optional().describe("거래유형(구매) 부가세코드"),
      MANAGE_BOND_NO: z.string().optional().describe("채권번호관리 (B:기본설정, M:필수입력, Y:선택입력, N:사용안함)"),
      MANAGE_DEBIT_NO: z.string().optional().describe("채무번호관리 (B:기본설정, M:필수입력, Y:선택입력, N:사용안함)"),
      CUST_LIMIT: z.string().optional().describe("거래처별여신한도"),
      O_RATE: z.string().optional().describe("출고조정률"),
      I_RATE: z.string().optional().describe("입고조정률"),
      PRICE_GROUP: z.string().optional().describe("영업단가그룹"),
      PRICE_GROUP2: z.string().optional().describe("구매단가그룹"),
      CUST_LIMIT_TERM: z.string().optional().describe("여신기간 (최대 365일)"),
    },
    annotations: { readOnlyHint: false, destructiveHint: false },
  },
  {
    name: "ecount_master_save_product",
    description:
      "ECOUNT ERP에 품목을 등록하거나 수정합니다. 새 품목을 추가하거나 기존 품목 정보를 변경할 때 사용합니다.",
    endpoint: "InventoryBasic/SaveBasicProduct",
    type: "save",
    listKey: "ProductList",
    inputSchema: {
      PROD_CD: z.string().describe("품목코드"),
      PROD_DES: z.string().describe("품목명"),
      SIZE_DES: z.string().optional().describe("규격"),
      UNIT: z.string().optional().describe("단위"),
      PROD_TYPE: z.string().optional().describe("품목구분"),
      BAL_FLAG: z.string().optional().describe("재고관리여부"),
      IN_PRICE: z.string().optional().describe("입고단가"),
      OUT_PRICE: z.string().optional().describe("출고단가"),
      BAR_CODE: z.string().optional(),
      CLASS_CD: z.string().optional().describe("분류코드"),
      REMARKS: z.string().optional().describe("비고"),
      OUT_PRICE_VAT: z.string().optional().describe("출고단가VAT포함여부 (0:미포함, 1:포함)"),
      IN_PRICE_VAT: z.string().optional().describe("입고단가VAT포함여부 (0:미포함, 1:포함)"),
      REMARKS_WIN: z.string().optional().describe("검색창내용"),
      CLASS_CD2: z.string().optional().describe("품목그룹2코드"),
      CLASS_CD3: z.string().optional().describe("품목그룹3코드"),
      TAX: z.string().optional().describe("부가가치세율(매출)"),
      VAT_RATE_BY: z.string().optional().describe("부가세율(매입)"),
      CS_FLAG: z.string().optional().describe("C-Portal사용여부 (1:사용, 0:미사용)"),
      INSPECT_TYPE_CD: z.string().optional().describe("품질검사유형"),
      INSPECT_STATUS: z.string().optional().describe("품질검사방법 (L:전수, S:샘플링)"),
      ITEM_TYPE: z.string().optional().describe("관리항목 (B:기본설정, M:필수입력, Y:선택입력, N:사용안함)"),
      SERIAL_TYPE: z.string().optional().describe("시리얼/로트 (B:기본설정, M:필수입력, Y:선택입력, N:사용안함)"),
    },
    annotations: { readOnlyHint: false, destructiveHint: false },
  },
  {
    name: "ecount_master_view_product",
    description:
      "ECOUNT ERP 특정 품목의 상세 정보를 조회합니다. 품목 코드로 단일 품목의 전체 정보를 확인할 때 사용합니다.",
    endpoint: "InventoryBasic/ViewBasicProduct",
    type: "query",
    inputSchema: {
      PROD_CD: z.string().describe("품목코드"),
      PROD_TYPE: z.string().optional().describe("품목구분"),
      COMMA_FLAG: z.string().optional().describe("Comma포함여부 (Y/N, 기본값 N)"),
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "ecount_master_list_products",
    description:
      "ECOUNT ERP 품목 목록을 조회합니다. 전체 품목 목록이나 특정 조건의 품목을 검색할 때 사용합니다.",
    endpoint: "InventoryBasic/GetBasicProductsList",
    type: "query",
    inputSchema: {
      PROD_CD: z.string().optional().describe("품목코드"),
      PROD_TYPE: z.string().optional().describe("품목구분"),
      FROM_PROD_CD: z.string().optional().describe("품목코드 시작 범위"),
      TO_PROD_CD: z.string().optional().describe("품목코드 종료 범위"),
      COMMA_FLAG: z.string().optional().describe("Comma포함여부 (Y/N, 기본값 N)"),
    },
    annotations: { readOnlyHint: true },
  },
];

export function registerMasterDataTools(server: McpServer, client: EcountClient): void {
  registerTools(server, client, masterDataTools);
}
