import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { EcountClient } from "../client/ecount-client.js";
import { registerTools, type ToolDefinition } from "./tool-factory.js";

const salesTools: ToolDefinition[] = [
  {
    name: "ecount_sales_save_quotation",
    description:
      "ECOUNT ERP 견적서를 저장합니다. 거래처에게 제품 견적을 등록하거나 수정할 때 사용합니다.",
    endpoint: "Quotation/SaveQuotation",
    type: "save",
    listKey: "QuotationList",
    inputSchema: {
      PROD_CD: z.string().describe("품목코드"),
      QTY: z.string().describe("수량"),
      UPLOAD_SER_NO: z.string().optional().describe("전표번호 (수정 시 사용)"),
      IO_DATE: z.string().optional().describe("견적일자 (YYYYMMDD)"),
      CUST: z.string().optional().describe("거래처코드"),
      WH_CD: z.string().optional().describe("창고코드"),
      PRICE: z.string().optional(),
      SUPPLY_AMT: z.string().optional().describe("공급가액"),
      VAT_AMT: z.string().optional(),
      REMARKS: z.string().optional(),
      CUST_DES: z.string().optional().describe("거래처명"),
      EMP_CD: z.string().optional().describe("담당자코드"),
      IO_TYPE: z.string().optional().describe("구분(거래유형) 부가세유형코드"),
      EXCHANGE_TYPE: z.string().optional().describe("외화종류 코드"),
      EXCHANGE_RATE: z.string().optional(),
      PJT_CD: z.string().optional().describe("프로젝트코드"),
      DOC_NO: z.string().optional().describe("견적No."),
      TTL_CTT: z.string().optional().describe("제목"),
      REF_DES: z.string().optional().describe("참조"),
      COLL_TERM: z.string().optional().describe("결제조건"),
      AGREE_TERM: z.string().optional().describe("유효기간"),
      PROD_DES: z.string().optional().describe("품목명"),
      SIZE_DES: z.string().optional().describe("규격"),
      UQTY: z.string().optional().describe("추가수량"),
      USER_PRICE_VAT: z.string().optional().describe("단가(VAT포함)"),
      SUPPLY_AMT_F: z.string().optional().describe("공급가액(외화)"),
      ITEM_CD: z.string().optional().describe("관리항목코드"),
    },
    annotations: { readOnlyHint: false, destructiveHint: false },
  },
  {
    name: "ecount_sales_save_sale_order",
    description:
      "ECOUNT ERP 수주(판매 주문)를 저장합니다. 고객으로부터 받은 주문을 등록하거나 수정할 때 사용합니다.",
    endpoint: "SaleOrder/SaveSaleOrder",
    type: "save",
    listKey: "SaleOrderList",
    inputSchema: {
      PROD_CD: z.string().describe("품목코드"),
      QTY: z.string().describe("수량"),
      UPLOAD_SER_NO: z.string().optional().describe("전표번호 (수정 시 사용)"),
      IO_DATE: z.string().optional().describe("수주일자 (YYYYMMDD)"),
      CUST: z.string().optional().describe("거래처코드"),
      WH_CD: z.string().optional().describe("창고코드"),
      PRICE: z.string().optional(),
      SUPPLY_AMT: z.string().optional().describe("공급가액"),
      VAT_AMT: z.string().optional(),
      REMARKS: z.string().optional(),
      TIME_DATE: z.string().optional().describe("납기일"),
      CUST_DES: z.string().optional().describe("거래처명"),
      EMP_CD: z.string().optional().describe("담당자코드"),
      IO_TYPE: z.string().optional().describe("구분(거래유형) 부가세유형코드"),
      EXCHANGE_TYPE: z.string().optional().describe("외화종류 코드"),
      EXCHANGE_RATE: z.string().optional(),
      PJT_CD: z.string().optional().describe("프로젝트코드"),
      DOC_NO: z.string().optional().describe("주문No."),
      PROD_DES: z.string().optional().describe("품목명"),
      SIZE_DES: z.string().optional().describe("규격"),
      UQTY: z.string().optional().describe("추가수량"),
      USER_PRICE_VAT: z.string().optional().describe("단가(VAT포함)"),
      SUPPLY_AMT_F: z.string().optional().describe("공급가액(외화)"),
      ITEM_CD: z.string().optional().describe("관리항목코드"),
    },
    annotations: { readOnlyHint: false, destructiveHint: false },
  },
  {
    name: "ecount_sales_save_sale",
    description:
      "ECOUNT ERP 매출전표를 저장합니다. 실제 판매(출하) 거래를 등록하거나 수정할 때 사용합니다.",
    endpoint: "Sale/SaveSale",
    type: "save",
    listKey: "SaleList",
    inputSchema: {
      PROD_CD: z.string().describe("품목코드"),
      QTY: z.string().describe("수량"),
      WH_CD: z.string().describe("출하창고코드"),
      UPLOAD_SER_NO: z.string().optional().describe("전표번호 (수정 시 사용)"),
      IO_DATE: z.string().optional().describe("판매일자 (YYYYMMDD)"),
      CUST: z.string().optional().describe("거래처코드"),
      CUST_DES: z.string().optional().describe("거래처명"),
      EMP_CD: z.string().optional().describe("담당사원코드"),
      PRICE: z.string().optional(),
      SUPPLY_AMT: z.string().optional().describe("공급가액"),
      VAT_AMT: z.string().optional(),
      REMARKS: z.string().optional(),
      PROD_DES: z.string().optional().describe("품목명"),
      SIZE_DES: z.string().optional().describe("규격"),
      IO_TYPE: z.string().optional().describe("구분(거래유형) 부가세유형코드"),
      EXCHANGE_TYPE: z.string().optional().describe("외화종류 코드"),
      EXCHANGE_RATE: z.string().optional(),
      PJT_CD: z.string().optional().describe("프로젝트코드"),
      UQTY: z.string().optional().describe("추가수량"),
      USER_PRICE_VAT: z.string().optional().describe("단가(VAT포함)"),
      SUPPLY_AMT_F: z.string().optional().describe("공급가액(외화)"),
      ITEM_CD: z.string().optional().describe("관리항목코드"),
    },
    annotations: { readOnlyHint: false, destructiveHint: false },
  },
];

export function registerSalesTools(server: McpServer, client: EcountClient): void {
  registerTools(server, client, salesTools);
}
